# Generated by Django 2.1.3 on 2018-11-03 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Camionero',
            new_name='Piloto',
        ),
    ]
