# Generated by Django 2.1.3 on 2018-11-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0004_auto_20181102_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='marca',
            field=models.CharField(max_length=200),
        ),
    ]
