# Generated by Django 2.1.3 on 2018-11-04 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0005_auto_20181103_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paquete',
            old_name='Destinatario',
            new_name='destinatario',
        ),
    ]
