# Generated by Django 2.1.3 on 2018-11-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0007_auto_20181104_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='paquete',
            field=models.ManyToManyField(through='entrega.Asignacion', to='entrega.Paquete'),
        ),
    ]
