# Generated by Django 2.1.3 on 2018-11-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0008_auto_20181104_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='paquete',
            field=models.ManyToManyField(related_name='paquete', to='entrega.Paquete'),
        ),
    ]
